<?php

namespace App\Console\Commands;

use App\Models\Camera;
use App\Models\Event;
use App\Models\School;
use Illuminate\Console\Command;

class MockRealtime extends Command
{
    protected $signature = 'mock:realtime {--iterations=10 : How many mock events to emit}';
    protected $description = 'Generate mock realtime events for demo mode (blocked in production).';

    public function handle(): int
    {
        if (app()->environment('production')) {
            $this->error('Refusing to run in production.');
            return self::FAILURE;
        }
        $schools = School::with('cameras')->get();
        if ($schools->isEmpty()) {
            $this->warn('No schools yet — run db:seed first.');
            return self::FAILURE;
        }
        $types = ['aiva', 'fr', 'bat'];
        $severities = ['info', 'info', 'warn', 'critical'];
        $iterations = (int) $this->option('iterations');
        for ($i = 0; $i < $iterations; $i++) {
            $school = $schools->random();
            $cam = $school->cameras->first();
            Event::create([
                'school_id' => $school->id,
                'camera_id' => $cam?->id,
                'type' => $types[array_rand($types)],
                'severity' => $severities[array_rand($severities)],
                'title' => 'Mock event #'.rand(1000, 9999),
                'description' => 'Auto-generated by mock:realtime',
                'status' => 'open',
                'detected_at' => now(),
            ]);
            if ($cam) {
                $cam->update(['online' => (bool) random_int(0, 1), 'last_seen_at' => now()]);
            }
        }
        $this->info("Emitted {$iterations} mock events.");
        return self::SUCCESS;
    }
}
